### ISSUE TITLE
ModuleNotFoundError: No module named 'crypto_pb2'

### ISSUE THREAD

**Issue by ghost** [martindbp/ipvc#4]
```
Traceback (most recent call last):
  File "/usr/bin/ipvc", line 33, in <module>
    sys.exit(load_entry_point('ipvc==0.1.3', 'console_scripts', 'ipvc')())
  File "/usr/bin/ipvc", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/ipvc-0.1.3-py3.10.egg/ipvc/__init__.py", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/ipvc-0.1.3-py3.10.egg/ipvc/cli.py", line 9, in <module>
  File "/usr/lib/python3.10/site-packages/ipvc-0.1.3-py3.10.egg/ipvc/ipvc_api.py", line 7, in <module>
  File "/usr/lib/python3.10/site-packages/ipvc-0.1.3-py3.10.egg/ipvc/repo.py", line 6, in <module>
  File "/usr/lib/python3.10/site-packages/ipvc-0.1.3-py3.10.egg/ipvc/common.py", line 18, in <module>
ModuleNotFoundError: No module named 'crypto_pb2'
```

**Comment by mayinrain** [comment]
If you are using pycharm, you can set the root folder to sources root
